# Generated by Django 3.1.4 on 2020-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_profile_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
